custom_components/dahua/__init__.py
custom_components/dahua/binary_sensor.py
custom_components/dahua/client.py
custom_components/dahua/thread.py

Add cross line detection support. 
Addresses https://github.com/rroller/dahua/issues/13
NOTE: This needs the camera's IVS SmartPlan to be enabled

Add cross line detection support

---

custom_components/dahua/__init__.py
custom_components/dahua/binary_sensor.py
custom_components/dahua/config_flow.py
custom_components/dahua/const.py

Adds a binary sensor for each configured event during the config flow of setting up the camera in HA and generalizes the code and reduces duplication.
Addresses https://github.com/rroller/dahua/issues/17

Support binary sensors for all configured events

---

custom_components/dahua/__init__.py
custom_components/dahua/binary_sensor.py
custom_components/dahua/const.py
custom_components/dahua/thread.py
custom_components/dahua/vto.py
requirements.txt

Add support for VTO (doorbell) events
Thanks to https://github.com/elad-bar/DahuaVTO2MQTT for the code I copied to pull events from the VTO (which is different form most Dahua cams)

Add support for VTO (doorbell) events

---

custom_components/dahua/__init__.py
custom_components/dahua/entity.py
custom_components/dahua/light.py

Fix entity_id renaming after entity renames

Fix entity_id renaming after entity renames

---

custom_components/dahua/__init__.py
custom_components/dahua/config_flow.py
custom_components/dahua/const.py
custom_components/dahua/translations/en.json

* Add config option to set camera name
* Set CONNECTION_CLASS = CONN_CLASS_LOCAL_POLL
* Only allow a camera to be added to HA once
* Log error during setup if connection to camera isn't successful

Add config option to set camera name

---

custom_components/dahua/translations/es.json

Spanish translation of the interface

Translation es

---

custom_components/dahua/translations/ca.json

Catalan translation of the interface

Catalan translation

---

custom_components/dahua/__init__.py
custom_components/dahua/config_flow.py
custom_components/dahua/rpc2.py
custom_components/dahua/thread.py

Start migration to the RPC2 API

Start migration to the RPC2 API

---

custom_components/dahua/__init__.py
custom_components/dahua/client.py
custom_components/dahua/config_flow.py
custom_components/dahua/rpc2.py

Support https with self signed certs.
This makes the assumption that folks are running https over port 443. If it turns out other ports are used then I'll add an option. This is a quick fix.
https://github.com/rroller/dahua/issues/51

Support https with self signed certs

---

README.md
custom_components/dahua/camera.py
custom_components/dahua/client.py
custom_components/dahua/services.yaml

Add support to open doors via a VTO
https://github.com/rroller/dahua/issues/53

Add support to open doors via a VTO

---

custom_components/dahua/__init__.py
custom_components/dahua/client.py

https://github.com/rroller/dahua/issues/9

Don't fail if device doesn't support lighting

---

custom_components/dahua/__init__.py
setup.cfg

https://github.com/rroller/dahua/issues/9

Support events per channel (fix DVR/NVR events)

---

custom_components/dahua/__init__.py
custom_components/dahua/binary_sensor.py

Fire the SmartMotionHuman event instead of the CrossLineDetection when a human is detected
https://github.com/rroller/dahua/issues/52

Fire the SmartMotionHuman event instead of the CrossLineDetection when a human is detected

---

custom_components/dahua/translations/pt_br.json

Please, add brazilian portuguese translation

Add brazilian portuguese translation

---

custom_components/dahua/client.py

Generic RTSP Camera support
1. Added exception with default values.
2. Return value for _get_max_extra_streams()_ changed from **2** to **3**
3. Return value for _get_rtsp_stream_url()_ changed for **subtype==3**
4. For clean RTSP during setup camera value of Address must provide like _192.168.17.12/stream1_
5. Entity for clean RTSP-stream is **sub_3**, for example _rtsp_camera_3_sub_3_, _outdoor_camera_sub_3_

Generic RTSP Camera support update client.py

---

custom_components/dahua/__init__.py

Created a patch for #202 / #203.
The fix is based on https://github.com/PeteRager/lennoxs30api/commit/e92907036a385050f9d73df0b813edbffa3a957f fixing a similar issue for another integration.

Use custom SSL context to specify cipher

---

custom_components/dahua/__init__.py

Fix detection DHI_NVR as doorbell
#241

Fix detecting DHI_NVR as doorbell 

---

README.md
custom_components/dahua/camera.py
custom_components/dahua/client.py
custom_components/dahua/services.yaml

This pull request add the service to adjact focus and zoom level as described in #205.
I tested with my IPC-HDW2431T-ZS-S2 and it works very well.

Add zoom focus control

---

custom_components/dahua/__init__.py

From https://github.com/rroller/dahua/pull/164 thanks to @ozziii

Add TAG reader thanks to @ozziii

---

custom_components/dahua/__init__.py

Add support for empiretech doorbell

---

custom_components/dahua/__init__.py

VTOs dont have a channel 0 on RTSP stream but do have a channel 0 for snapshots?
so this just checks if not a doorbell and sets back to 0

set vto rtsp channel correctly

---

README.md

I have an Amcrest AD110 running smoothly with this integration. The only reason this doorbell might seem to not work is because it requires a specific firmware version installed for the doorbell API to function at all (https://www.reddit.com/r/homeassistant/comments/nttciw/comment/ijat032/)
Thanks for the great work!

Document support for Amcrest AD110

---

custom_components/dahua/__init__.py

Modified the or to add a starts with on the model looking for IP8M  in the model name.

Update __init__.py added support for IP8M type camera like model IP8M-2796E-AI 

---

custom_components/dahua/__init__.py
custom_components/dahua/client.py
custom_components/dahua/const.py
custom_components/dahua/switch.py

More details: https://github.com/rroller/dahua/issues/398

Add event notifications boolean switch

---

.devcontainer.json
scripts/setup

https://code.visualstudio.com/remote/advancedcontainers/docker-options#_podman

Changes to allow using podman

---

custom_components/dahua/__init__.py

Added support for the Imou DB61i which is identical to the Amcrest AD410.

Add support for Imou DB61i same as Amcrest AD410.

---

README.md
custom_components/dahua/__init__.py
custom_components/dahua/camera.py
custom_components/dahua/client.py
custom_components/dahua/select.py
custom_components/dahua/services.yaml

Support added for PTZ cameras. There is a new entity that allows you to move the camera to a preset position (only 1 to 10 positions are supported). Useful when you want that your camera points to a specific point based on some conditions.

PTZ Support
