- custom_components/dahua/vto.py
This fixes the bug described in #52 - the `table` variable is None and thus the for loop throws an exception. See here: https://github.com/rroller/dahua/blob/9910d0d/custom_components/dahua/vto.py#L256
> vto: don't attempt to iterate over an empty table

- custom_components/dahua/__init__.py
- custom_components/dahua/camera.py
- custom_components/dahua/client.py
- custom_components/dahua/translations/en.json
I have an eight channel Lorex NVR (along with various Amcrest/Loryta) cams. Unfortunately, four of the lorex cams are still using the PoE on the NVR. 
Lorex is returning "31" for the model, but has the model in the unqueSerial field. Also, the day/night mode access through the NVR uses a different method. The Dahua method works on the direct connected NVRs, but not through the Lorex firmware.
> Support for Lorex E891AB NVR

- custom_components/dahua/__init__.py
- custom_components/dahua/client.py
- custom_components/dahua/light.py
Resolves issue #151 
For Amcrest Flood Lights table.Lighting_V2[channel][profile_mode][0] points to 'Infrared'.
Added ASH26 specific data checks, classes and methods for table.Lighting_V2[channel][profile_mode][1] which is for 'WhiteLight'.
Also, changing the brightness (like in the Dahua Illuminator) seems to cause errors within the device it self and invalidates the light on/off command entirely.
> Added support for Amcrest Flood Lights (ASH26)

- custom_components/dahua/config_flow.py
I have an IPC-T5442T-ZE running on firmware V2.840.15OG008.0.R (Build Date: 2022-02-18). I wanted to use the "Smart Object Detection" feature via this integration to detect when packages were left and removed. Initially I tried to do this by selecting the `TakenAwayDetection` and `LeftDetection` events but that didn't do anything. After some digging I realized its because my camera fires events with codes `ObjectRemovalDetection` and `ObjectPlacementDetection` here.
I'm not sure if this changed in newer firmware or different models do different things so I didn't modify the existing events. But it would be good if these two could get added to the list so folks like myself could use them.
> Add `ObjectRemovalDetection` and `ObjectPlacementDetection`

- custom_components/dahua/__init__.py
Hi, my VTO-2211-P was not detected as doorbell. Device name is DH-VTO2211G-P (it doesn't match VTO-* DHI-* etc.)
Firmware version is 4.511.0000000.0.R,build:2021-11-16.
This is probably related to https://github.com/rroller/dahua/issues/61
Now it's detected as doorbell and the binary sensor works.
Thank you very much for this integration
> Detect VTO-2211 (newer firmware?) as doorbell

- custom_components/dahua/__init__.py
SmartMotionHuman is triggered as a separate event from CrossLineDetection and CrossRegionDetection. These should only be translated when listeners for the more specific entities are not present.
Resolves #138
Resolves #189
> Fix tripwire and intrusion entities

- custom_components/dahua/__init__.py
A bit of cleanup around log messages and error handling when connection to a camera fails (e.g., the camera isn't plugged in). The component used to add a lot of long stack trace and error messages if a connection error happened. Now it's more like a single warning line saying the connection failed (with host & port).
> Reduce error message verbosity for simple connection errors

- README.md
- custom_components/dahua/vto.py
I had some issues running this integration with DHI-VTO3311Q-WP. After some time, the integration stopped working and I had to restart homeassistant to fix it.
After some debugging, it turns out that asyncio does not forward the entire message to the data_received function if the message is too large. In turn this sometimes messes up the future messages and the integration stops working. To remedy that, I added a buffer to the data_received function.
During debugging I also noticed that data_handlers is growing due to keep_alive handlers being added constantly. To fix that I added code to remove the handler after response from keep-alive has been received. I don't think this has anything to do with the above issue, however I still think it should be fixed.
And for the last change - I …
> VTO buffer and keepalive fix

- custom_components/dahua/__init__.py
- custom_components/dahua/client.py
- custom_components/dahua/light.py
Hi, Lightingv2 doesn't trigger the floodlights in the later Dahua model L46N.  After some exploration and comparison to DMSS call status, it appears that the manual floodlight trigger is only available through the coaxial API.  This also requires the table.FloodlightMode.mode to be set to manual or at least not motion detection to stay on.  I tried to add it along side the Amcrest work assuming it still works for the older model.
> Add support for L46N floodlights and possibly the Lorex equivalent

- custom_components/dahua/client.py
the checker is looking for the wrong spelling
checked my XVR (BNC) and its showing 1 extra stream `table.MaxExtraStream=1`
checked my NVR (IP) which returns 2 extra stream `table.MaxExtraStream=2`
also fixes my other issue where the XVR keeps returning 3 streams
because it cant find the value so just assumes its 2 extra streams when really it should be 1
> fix MaxExtraStream spelling

- custom_components/dahua/binary_sensor.py
This fixes the bellow issue in HA `2024.5.0`. 
```
Failed to handle event, error: Detected that custom integration 'dahua' calls async_write_ha_state from a thread at custom_components/dahua/__init__.py, line 397: listener(). Please report it to the author of the 'dahua' custom integration., Line: 125
Failed to handle event, error: Detected that custom integration 'dahua' calls async_write_ha_state from a thread at custom_components/dahua/__init__.py, line 414: listener(). Please report it to the author of the 'dahua' custom integration., Line: 125
```
> fix(binary_sensor): changes async_write_ha_state method to schedule_update_ha_state in is_on()

- custom_components/dahua/camera.py
- hacs.json
- requirements.txt
Since HA core 2024.1.0 `supported_features` should use the `CameraEntityFeature` `IntFlag`
https://developers.home-assistant.io/docs/core/entity/camera/#supported-features
`SUPPORT_STREAM` will be removed in HA Core 2025.1
Fixes https://github.com/rroller/dahua/issues/328
PR for fixing Light deprecated constants will follow
> Fix HA camera deprecated constant

- custom_components/dahua/camera.py
I recently purchased an IPC-Color4K-T-2.8mm and while integrating it with Home Assistant, the call to flip between day and night mode was failing with a "501 Not Implemented", after looking at some tcpdump traffic and also the ipcamtalk forums, this camera seems to use the newer web 5.0 interface. I found a string in the forums that worked. Originally i modified the call `async_set_video_profile_mode`, and that worked, but then i noticed that the call for `async_set_night_switch_mode` is basically the same code as what i had modified.
I went back and found the logic in camera.py on line 319 and added part of this camera model there (they also make an X model and a 3.6mm version of each, so i trimmed the model name a bit). Not sure if this model logic should be handled in a different way, …
> Update night switch mode for specific NVR and IPC models

- custom_components/dahua/camera.py
I had recently updated my integrations and noticed that my day/night mode was no longer working. I traced it to a bug that was introduced in https://github.com/rroller/dahua/pull/327 - Non-empty Python strings are always truthy, so this statement always evaluates to `True`:
```
if 'NVR4108HS' or 'IPC-Color4K' in model:
```
This PR correctly searches the model string and uses an array to make it easier to add more models in the future.
> Fix day/night mode switch

- custom_components/dahua/__init__.py
- custom_components/dahua/light.py
At the risk of pestering, I am going to make another PR, as it seems this issue continues to get overlooked and the previous pull request (by another user) was never merged.
I was experiencing the issue that was possibly solved with [PR 315](https://github.com/rroller/dahua/pull/315) for the ability to control the light on my ASH26-W floodlight. Using that fork I was able to get my floodlight to work. However, it was very much an older version and the doorbell button on my AD410 would not trigger in home assistant.
I simply took the changes made to that pull request, applied them to the main branch 0.9.59, and have been using this fork for roughly a week with no issue. 
I do not have any other devices aside from my ASH26-W and my AD410, so I am not positive if these changes will break …
> making the changes from PR 315 to the most recent release (0.9.59) to solve floodlight control 

- custom_components/dahua/__init__.py
- custom_components/dahua/client.py
- custom_components/dahua/config_flow.py
Fix hassio warning about blocking SSL setup `Detected blocking call to load_default_certs`  and
`setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done`
Also fixed approach how to detect if DisableLinkage feature is present which return false True (positive) even when the feature is not present in the camera and direct cgi-bin call return 400 error.
> Fix hassio warnings and false True (positive) for DisableLinkage feature

- custom_components/dahua/__init__.py
Added check for Lighing_V2 support and API call if it supported in init.py
Also edit check for infrared light support. IPC-HFW2439SP-SA-LED-S2 has no infrared light but it was found by integration.
> Illuminator support for IPC-HFW2439SP-SA-LED-S2

- custom_components/dahua/light.py
- Removed `supported_features` (return 0) from Illuminator. Fixing deprecation mentioned in https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation/ Fixes #443 and #438  
- Added `supported_color_modes` to Illuminator. Fixing deprecation mentioned in https://developers.home-assistant.io/blog/2024/02/12/light-color-mode-mandatory/ Fixes #438 
- Also added `color_mode` and `supported_color_modes` to FloodLight.
> Deprecation fixes for Illuminator and FloodLight

- custom_components/dahua/config_flow.py
This is a fix for #440 and removes the deprecated option of setting the self.config_entry in the OptionsFlowHandler (see https://developers.home-assistant.io/blog/2024/11/12/options-flow/)
Successfully tested locally
> Removed manual setting of self.config_entry

- custom_components/dahua/__init__.py
- custom_components/dahua/manifest.json
- custom_components/dahua/services.yaml
I noticed that my previous PRs failed the hassfest validation on existing code. This change should bring that code in line with the hassfest checks.
```
Error: R] [DEPENDENCIES] Using component tag but it's not in 'dependencies' or 'after_dependencies'
```
- Fixed in `manifest.json` by adding `tag` to `after_dependencies`. It was triggered because of `from homeassistant.components.tag import async_scan_tag` in `__init__.py`. Added the `after_dependencies` makes sure that the home assistant tag component is loaded before the Dahua integration. 
- Also reordered the fields in `manifest.json` as "Manifest keys should be sorted: domain, name, then alphabetical order"
```
Error: R] [SERVICES] Service set_infrared_mode has a field mode with no name and is not in the translations file
Error: R] …
```
> Fixing hassfest validation

- custom_components/dahua/client.py
Currently integration doesn't support password with special characters because there is no proper escaping of characters
Added password and username url escaping to make it possible to use special chars in password
> Added password and username url escaping to make it possible to use special chars in password

- requirements_test.txt
All tests have been failing with:
```
AttributeError: module 'josepy' has no attribute 'ComparableX509'
```
Update `pytest-homeassistant-custom-component` from 0.13.133 to 0.13.286 to resolve compatibility with newer josepy versions.
Verified locally that pytest can now import dependencies and collect tests without errors.
> Update pytest-homeassistant-custom-component to fix test failures

- custom_components/dahua/__init__.py
- custom_components/dahua/client.py
Moves timeout fix from request level (#501) to session level, which is more appropriate since the session is created specifically for the Dahua client.
- Add `timeout=ClientTimeout(total=None)` to ClientSession creation in `__init__.py`
- Revert request-level timeout fix from `client.py`
The session-level fix prevents the default 5-minute timeout from disconnecting infinite event streams while keeping regular API requests properly scoped.
Tested in production with no timeout errors.
> Fix event stream timeout at session level
